import { StyleSheet } from 'react-native';

export const green = '#11BD88';
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F8FAFC' },
  splashScreen: { backgroundColor: '#F8FAFC' },
  lightSplashContainer: { flex: 1, backgroundColor: '#F8FAFC', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 50, paddingHorizontal: 24 },
  lightSplashLogoDark: { color: '#0F172A', fontSize: 36, fontWeight: '900', letterSpacing: -0.5 },
  lightSplashLogoGreen: { color: '#10B981', fontSize: 36, fontWeight: '900', letterSpacing: -0.5 },
  lightSplashTaglineSub: { color: '#64748B', fontSize: 16, fontWeight: '500', textAlign: 'center' },
  lightSplashIncomeText: { color: '#059669', fontSize: 13, fontWeight: '700', marginTop: 6 },
  lightSplashExpenseText: { color: '#DC2626', fontSize: 13, fontWeight: '700', marginTop: 6 },
  lightSplashTaglineBold: { color: '#10B981', fontSize: 18, fontWeight: '800', letterSpacing: 0.3, textAlign: 'center' },
  lightSplashTaglineSmall: { color: '#64748B', fontSize: 15, fontWeight: '500', marginTop: 4, textAlign: 'center' },
  onboardingHeaderRow: { position: 'absolute', top: 50, left: 24, right: 24, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', zIndex: 10 },
  skipButtonTopRight: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 14, backgroundColor: '#F1F5F9' },
  skipTextTopRight: { color: '#64748B', fontSize: 14, fontWeight: '700' },
  onboardingBackButton: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 14, backgroundColor: '#F1F5F9' },
  onboardingBackText: { color: '#64748B', fontSize: 14, fontWeight: '700' },
  splashContainer: { flex: 1, alignItems: 'center', justifyContent: 'space-between', paddingVertical: 50, paddingHorizontal: 24 },
  splashHeader: { alignItems: 'center', marginTop: 30 },
  splashLogoRow: { flexDirection: 'row', alignItems: 'center', marginTop: 16 },
  splashLogoWhite: { color: '#FFFFFF', fontSize: 36, fontWeight: '900', letterSpacing: -0.5 },
  splashLogoGreen: { color: '#10B981', fontSize: 36, fontWeight: '900', letterSpacing: -0.5 },
  splashUnderlineBar: { width: 44, height: 3.5, backgroundColor: '#10B981', borderRadius: 2, marginTop: 8, marginBottom: 12 },
  splashTaglineSub: { color: '#94A3B8', fontSize: 16, fontWeight: '500', textAlign: 'center' },
  splashHeroContainer: { width: '100%', height: 230, alignItems: 'center', justifyContent: 'center', position: 'relative' },
  splashBadgeLeft: { position: 'absolute', left: 16, bottom: 45, alignItems: 'center' },
  splashBadgeRight: { position: 'absolute', right: 16, bottom: 45, alignItems: 'center' },
  splashIncomeCircle: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#10B981', alignItems: 'center', justifyContent: 'center', shadowColor: '#10B981', shadowOpacity: 0.4, shadowRadius: 10, elevation: 4 },
  splashExpenseCircle: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#EA580C', alignItems: 'center', justifyContent: 'center', shadowColor: '#EA580C', shadowOpacity: 0.4, shadowRadius: 10, elevation: 4 },
  splashIncomeText: { color: '#A7F3D0', fontSize: 13, fontWeight: '700', marginTop: 6 },
  splashExpenseText: { color: '#FDBA74', fontSize: 13, fontWeight: '700', marginTop: 6 },
  splashFooter: { alignItems: 'center', marginBottom: 20 },
  splashDotsRow: { flexDirection: 'row', gap: 8, marginBottom: 24 },
  splashDotActive: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#10B981' },
  splashDotInactive: { width: 10, height: 10, borderRadius: 5, backgroundColor: 'rgba(255, 255, 255, 0.2)' },
  splashTaglineBold: { color: '#10B981', fontSize: 16, fontWeight: '800', letterSpacing: 0.3, textAlign: 'center' },
  splashTaglineSmall: { color: '#CBD5E1', fontSize: 15, fontWeight: '500', marginTop: 4, textAlign: 'center' },
  splashContent: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingBottom: 28 },
  iconTile: { width: 98, height: 98, borderRadius: 28, backgroundColor: 'rgba(255,255,255,0.18)', alignItems: 'center', justifyContent: 'center', marginBottom: 32 },
  wallet: { width: 43, height: 38, position: 'relative' },
  walletBody: { position: 'absolute', left: 0, bottom: 0, width: 39, height: 32, borderWidth: 3, borderColor: '#fff', borderRadius: 5 },
  walletFlap: { position: 'absolute', right: 0, top: 11, width: 17, height: 15, borderWidth: 3, borderColor: '#fff', borderRadius: 4, backgroundColor: '#38C198', alignItems: 'flex-end', justifyContent: 'center', paddingRight: 2 },
  walletDot: { width: 3, height: 3, borderRadius: 2, backgroundColor: '#fff' },
  splashTitle: { color: '#fff', fontSize: 36, fontWeight: '800', letterSpacing: -1.1, lineHeight: 43 },
  splashSubtitle: { color: 'rgba(255,255,255,0.82)', fontSize: 18, marginTop: 9 },
  onboarding: { flex: 1, backgroundColor: '#F8FAFC', paddingHorizontal: 25, paddingTop: 100 },
  skipButton: { alignSelf: 'flex-end', marginTop: 88, padding: 6 },
  skipText: { color: '#94A3B8', fontSize: 14 },
  slideContent: { flex: 1, alignItems: 'center', paddingTop: 36 },
  illustration: { width: 192, height: 192, borderRadius: 96, backgroundColor: '#E0FAF1', alignItems: 'center', justifyContent: 'center', shadowColor: '#B4EAD8', shadowOpacity: 0.45, shadowRadius: 26, shadowOffset: { width: 0, height: 8 }, elevation: 2 },
  rupee: { color: green, fontSize: 76, fontWeight: '400', marginTop: -4 },
  heading: { marginTop: 48, color: '#172033', fontSize: 31, lineHeight: 38, fontWeight: '800', letterSpacing: -0.7, textAlign: 'center' },
  description: { marginTop: 14, color: '#68758B', fontSize: 18, lineHeight: 30, textAlign: 'center' },
  bottomArea: { paddingBottom: 48, alignItems: 'center' },
  pagination: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 32 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#E1E7EC' },
  skipButton: { alignSelf: 'flex-end', marginTop: 88, padding: 6 },
  skipText: { color: '#94A3B8', fontSize: 14 },
  slideContent: { flex: 1, alignItems: 'center', paddingTop: 46 },
  illustration: { width: 192, height: 192, borderRadius: 96, backgroundColor: '#E0FAF1', alignItems: 'center', justifyContent: 'center', shadowColor: '#B4EAD8', shadowOpacity: 0.45, shadowRadius: 26, shadowOffset: { width: 0, height: 8 }, elevation: 2 },
  rupee: { color: green, fontSize: 76, fontWeight: '400', marginTop: -4 },
  heading: { marginTop: 48, color: '#172033', fontSize: 31, lineHeight: 38, fontWeight: '800', letterSpacing: -0.7, textAlign: 'center' },
  description: { marginTop: 14, color: '#68758B', fontSize: 18, lineHeight: 30, textAlign: 'center' },
  bottomArea: { paddingBottom: 48, alignItems: 'center' },
  pagination: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 32 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#E1E7EC' },
  activeDot: { width: 32, backgroundColor: green },
  primaryButton: { width: '100%', height: 55, borderRadius: 14, backgroundColor: green, alignItems: 'center', justifyContent: 'center', shadowColor: '#0BA576', shadowOpacity: 0.32, shadowRadius: 12, shadowOffset: { width: 0, height: 7 }, elevation: 5 },
  pressedButton: { opacity: 0.84, transform: [{ scale: 0.985 }] },
  primaryButtonText: { color: '#fff', fontSize: 17, fontWeight: '800' },
  home: { flex: 1, backgroundColor: '#F8FAFC' },
  homeHero: { backgroundColor: '#0FBD89', paddingHorizontal: 20, paddingTop: 40, paddingBottom: 36, borderBottomLeftRadius: 24, borderBottomRightRadius: 24 },
  homeTopRow: { flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 36, height: 36, borderRadius: 18, borderWidth: 1, borderColor: 'rgba(255,255,255,0.3)', backgroundColor: 'rgba(255,255,255,0.15)', alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  greeting: { marginLeft: 10, flex: 1 },
  greetingSmall: { color: 'rgba(255,255,255,0.78)', fontSize: 12 },
  greetingName: { color: '#fff', fontSize: 15, fontWeight: '800', marginTop: 1 },
  headerButtons: { flexDirection: 'row', gap: 8 },
  headerButton: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.13)', alignItems: 'center', justifyContent: 'center' },
  balanceLabel: { color: 'rgba(255,255,255,0.82)', fontSize: 13, textAlign: 'center', marginTop: 14 },
  balance: { color: '#fff', fontSize: 34, fontWeight: '800', textAlign: 'center', marginTop: 2, letterSpacing: -0.8 },
  summaryRow: { flexDirection: 'row', gap: 10, marginTop: 14 },
  summaryCard: { flex: 1, height: 64, borderRadius: 14, paddingVertical: 8, paddingHorizontal: 12, backgroundColor: 'rgba(255,255,255,0.20)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.15)' },
  summaryLabel: { color: 'rgba(255,255,255,0.78)', fontSize: 12 },
  summaryValue: { color: '#fff', fontSize: 16, fontWeight: '800', marginTop: 3 },
  homeMainScroll: { flex: 1 },
  homeMainScrollContent: { paddingBottom: 90 },
  homeSummarySection: { marginTop: -20, paddingHorizontal: 20, paddingBottom: 10 },
  stickyTransactionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#F8FAFC', paddingHorizontal: 20, paddingTop: 10, paddingBottom: 8 },
  transactionList: { paddingHorizontal: 20, paddingBottom: 20 },
  budgetCard: { backgroundColor: '#fff', borderRadius: 18, padding: 14, shadowColor: '#7C8798', shadowOpacity: 0.1, shadowRadius: 10, shadowOffset: { width: 0, height: 3 }, elevation: 3 },
  budgetHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  budgetTitle: { color: '#172033', fontSize: 15, fontWeight: '800' },
  budgetAmount: { color: '#8390A3', fontSize: 12, fontWeight: '700' },
  progressTrack: { height: 7, backgroundColor: '#EDF0F4', borderRadius: 4, marginTop: 10, overflow: 'hidden' },
  progressZero: { height: '100%', width: 0, backgroundColor: green },
  budgetHint: { color: '#95A0B0', fontSize: 11, marginTop: 6 },
  transactionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 16 },
  transactionTitle: { color: '#172033', fontSize: 17, fontWeight: '800' },
  seeAll: { color: green, fontSize: 13, fontWeight: '700' },
  emptyTransactions: { alignItems: 'center', marginTop: 20, paddingHorizontal: 20 },
  emptyIcon: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E4FAF2' },
  emptyIconText: { color: green, fontSize: 24, fontWeight: '700' },
  emptyTitle: { color: '#273247', fontSize: 15, fontWeight: '800', marginTop: 10 },
  emptyMessage: { color: '#8995A6', textAlign: 'center', lineHeight: 18, fontSize: 12, marginTop: 4 },
  navigation: { height: 68, backgroundColor: '#fff', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 28, shadowColor: '#8390A3', shadowOpacity: 0.08, shadowRadius: 10, shadowOffset: { width: 0, height: -2 }, elevation: 8 },
  navItem: { alignItems: 'center', width: 55, gap: 4 },
  navLabel: { color: '#99A3B3', fontSize: 11 },
  activeNavLabel: { color: green },
  floatingButton: { position: 'absolute', right: 24, bottom: 80, width: 52, height: 52, borderRadius: 26, backgroundColor: green, alignItems: 'center', justifyContent: 'center', shadowColor: '#0A956B', shadowOpacity: 0.34, shadowRadius: 11, shadowOffset: { width: 0, height: 6 }, elevation: 7 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(17, 27, 44, 0.35)', justifyContent: 'flex-end' },
  addSheet: { backgroundColor: '#fff', borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 25, paddingBottom: 36, alignItems: 'center' },
  sheetHandle: { width: 38, height: 4, borderRadius: 2, backgroundColor: '#D9DFE6', marginBottom: 22 },
  sheetTitle: { color: '#172033', fontSize: 21, fontWeight: '800' },
  sheetText: { color: '#68758B', fontSize: 15, textAlign: 'center', marginTop: 10, lineHeight: 22 },
  sheetClose: { backgroundColor: green, borderRadius: 12, height: 50, width: '100%', alignItems: 'center', justifyContent: 'center', marginTop: 24 },
  sheetCloseText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  transactionRow: { flexDirection: 'row', alignItems: 'center', padding: 10, marginTop: 8, borderRadius: 14, backgroundColor: '#fff', shadowColor: '#758198', shadowOpacity: 0.06, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  transactionCategoryIcon: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FEF2F2' },
  transactionCategorySymbol: { color: '#EF5A5A', fontSize: 20, fontWeight: '700' },
  transactionRowText: { flex: 1, marginLeft: 10, minWidth: 0 },
  transactionRowTitle: { color: '#1E293B', fontSize: 14, fontWeight: '800' },
  transactionRowSub: { color: '#8A96A7', fontSize: 11, marginTop: 1 },
  transactionRowNote: { color: '#68758B', fontSize: 11, marginTop: 1 },
  transactionAmount: { color: '#EF4D4D', fontSize: 15, fontWeight: '800', marginLeft: 8 },
  incomeAmount: { color: green },
  formScreen: { flex: 1, backgroundColor: green },
  formHero: { backgroundColor: green, paddingHorizontal: 20, paddingTop: 44, paddingBottom: 22 },
  formHeader: { height: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  formClose: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.18)' },
  headerBlank: { width: 38 },
  formTitle: { color: '#fff', fontSize: 17, fontWeight: '700', textAlign: 'center' },
  howMuch: { color: 'rgba(255,255,255,0.85)', textAlign: 'center', fontSize: 13, fontWeight: '600', marginTop: 12 },
  amountInputContainer: { alignSelf: 'center', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 8, paddingHorizontal: 16, paddingVertical: 4, backgroundColor: 'rgba(255,255,255,0.18)', borderRadius: 16, borderWidth: 1, borderColor: 'rgba(255,255,255,0.28)', minWidth: 190, maxWidth: 260 },
  currency: { color: '#fff', fontSize: 26, fontWeight: '800', marginRight: 6 },
  amountInput: { color: '#fff', fontSize: 32, fontWeight: '800', paddingVertical: 2, textAlign: 'center', flexShrink: 1 },
  formPanel: { flex: 1, marginTop: -5, backgroundColor: '#fff', borderTopLeftRadius: 28, borderTopRightRadius: 28 },
  formPanelContent: { flex: 1 },
  formPanelContentInner: { padding: 26, paddingBottom: 30 },
  typeToggle: { height: 49, padding: 3, backgroundColor: '#F1F3F6', borderRadius: 26, flexDirection: 'row' },
  typeOption: { flex: 1, borderRadius: 23, alignItems: 'center', justifyContent: 'center' },
  selectedType: { backgroundColor: '#fff', shadowColor: '#667085', shadowOpacity: 0.14, shadowRadius: 5, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  typeText: { color: '#737E8E', fontSize: 15, fontWeight: '700' },
  expenseTypeText: { color: '#EC5858' },
  incomeTypeText: { color: green },
  dateTimeRow: { flexDirection: 'row', gap: 12, marginTop: 17 },
  dateTimeButton: { flex: 1, backgroundColor: '#F8F9FB', borderRadius: 15, paddingHorizontal: 14, paddingVertical: 11 },
  dateTimeLabel: { color: '#929CAD', fontSize: 11, fontWeight: '700' },
  dateTimeValue: { color: '#273247', fontSize: 13, fontWeight: '800', marginTop: 4 },
  categoryHeading: { color: '#1D283A', fontSize: 16, fontWeight: '800', marginTop: 34, marginBottom: 16 },
  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 19, paddingBottom: 3 },
  categoryChoice: { width: '23%', alignItems: 'center' },
  categoryCircle: { width: 56, height: 56, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F7F8FA', borderWidth: 1.5, borderColor: 'transparent' },
  selectedCategory: { borderColor: '#F25B29', backgroundColor: '#FFFDF9' },
  categorySymbol: { color: '#98A2AE', fontSize: 26, fontWeight: '500' },
  selectedCategorySymbol: { color: '#EF592B' },
  categoryName: { color: '#68758B', fontSize: 11, marginTop: 7, textAlign: 'center' },
  noteInput: { height: 55, borderRadius: 15, backgroundColor: '#F8F9FB', color: '#273247', fontSize: 15, paddingHorizontal: 16, paddingVertical: 15, marginTop: 17, textAlignVertical: 'top' },
  saveButton: { height: 54, borderRadius: 14, backgroundColor: green, alignItems: 'center', justifyContent: 'center', marginTop: 12 },
  saveButtonText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  sectionCard: { backgroundColor: '#fff', borderRadius: 24, padding: 20, marginBottom: 20, shadowColor: '#7C8798', shadowOpacity: 0.08, shadowRadius: 20, shadowOffset: { width: 0, height: 6 }, elevation: 2 },
  sectionHeading: { color: '#172033', fontSize: 15, fontWeight: '800', marginBottom: 14 },
  listItem: { marginBottom: 14 },
  listLabel: { color: '#475569', fontSize: 13, fontWeight: '700', marginBottom: 8 },
  listValue: { color: '#475569', fontSize: 13, marginTop: 3 },
  listItemRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 6 },
  formRow: { flexDirection: 'row', gap: 12 },
  smallInputCard: { flex: 1, backgroundColor: '#F8F9FB', borderRadius: 18, padding: 14 },
  inputLabel: { color: '#475569', fontSize: 12, fontWeight: '700', marginBottom: 8 },
  budgetInput: { color: '#172033', fontSize: 16, fontWeight: '700' },
  toggleRow: { flexDirection: 'row', gap: 10, backgroundColor: '#F1F3F6', borderRadius: 26, padding: 4, marginBottom: 14 },
  detailsScreen: { flex: 1, backgroundColor: '#F8FAFC', paddingHorizontal: 20, paddingTop: 44 },
  detailsHeader: { height: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  detailBack: { width: 38, height: 38, borderRadius: 19, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', shadowColor: '#758198', shadowOpacity: 0.12, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  detailsTitle: { color: '#192338', fontSize: 17, fontWeight: '700', textAlign: 'center' },
  editAction: { color: green, fontSize: 14, fontWeight: '800', width: 38, textAlign: 'right' },
  detailCard: { backgroundColor: '#fff', borderRadius: 30, marginTop: 34, padding: 24, paddingTop: 39, shadowColor: '#7C8798', shadowOpacity: 0.12, shadowRadius: 14, shadowOffset: { width: 0, height: 5 }, elevation: 3 },
  detailPill: { position: 'absolute', top: -15, alignSelf: 'center', paddingHorizontal: 19, paddingVertical: 7, borderRadius: 17, backgroundColor: '#FDE8E8' },
  detailIncomePill: { backgroundColor: '#DDF8ED' },
  detailPillText: { color: '#EF5959', fontSize: 13, fontWeight: '800' },
  detailIncomeText: { color: green },
  detailCategoryCircle: { width: 63, height: 63, borderRadius: 18, backgroundColor: '#FBF3FF', alignSelf: 'center', alignItems: 'center', justifyContent: 'center' },
  detailCategorySymbol: { color: '#A043E7', fontSize: 29, fontWeight: '700' },
  detailCategory: { color: '#788497', fontSize: 16, textAlign: 'center', marginTop: 16 },
  detailAmount: { color: '#EE4D4D', fontSize: 35, fontWeight: '800', textAlign: 'center', marginTop: 5 },
  detailDivider: { height: 1, backgroundColor: '#EDF0F4', marginVertical: 27 },
  detailItem: { marginBottom: 18, paddingLeft: 43 },
  detailItemLabel: { color: '#929CAD', fontSize: 12 },
  detailItemValue: { color: '#1F2A3C', fontSize: 15, fontWeight: '800', marginTop: 3 },
  deleteButton: { marginTop: 15, height: 46, borderRadius: 14, backgroundColor: '#FEF2F2', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#FCA5A5' },
  deleteButtonText: { color: '#EF4444', fontSize: 14, fontWeight: '800' },
  reportsHeaderContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 44, paddingBottom: 16 },
  reportsTitle: { fontSize: 26, fontWeight: '800', color: '#0F172A' },
  monthSelector: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderRadius: 20, paddingHorizontal: 8, paddingVertical: 4, shadowColor: '#64748B', shadowOpacity: 0.08, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  monthNavButton: { paddingHorizontal: 8, paddingVertical: 2 },
  monthNavArrow: { fontSize: 18, color: '#64748B', fontWeight: '700' },
  monthLabel: { fontSize: 13, fontWeight: '700', color: '#1E293B', paddingHorizontal: 2 },
  reportsTabToggle: { flexDirection: 'row', backgroundColor: '#E2E8F0', borderRadius: 16, padding: 3, marginHorizontal: 20, marginBottom: 16 },
  reportsTabOption: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 8, borderRadius: 13 },
  reportsTabActive: { backgroundColor: '#fff', shadowColor: '#64748B', shadowOpacity: 0.1, shadowRadius: 4, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  reportsTabText: { fontSize: 13, fontWeight: '600', color: '#64748B' },
  reportsTabActiveText: { color: '#0F172A', fontWeight: '800' },
  reportsChartCard: { backgroundColor: '#fff', borderRadius: 24, padding: 20, marginHorizontal: 20, marginBottom: 16, shadowColor: '#64748B', shadowOpacity: 0.08, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
  donutWrapper: { alignItems: 'center', justifyContent: 'center', position: 'relative' },
  donutCenterLabel: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
  donutCenterTitle: { fontSize: 12, color: '#64748B', fontWeight: '600' },
  donutCenterAmount: { fontSize: 22, color: '#0F172A', fontWeight: '800', marginTop: 2 },
  legendGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginTop: 20, rowGap: 12 },
  legendItem: { width: '48%', flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendDot: { width: 10, height: 10, borderRadius: 5 },
  legendName: { fontSize: 12, color: '#475569', fontWeight: '600', flex: 1 },
  legendPercent: { fontSize: 12, color: '#0F172A', fontWeight: '800' },
  emptyLegendText: { color: '#94A3B8', fontSize: 13, textAlign: 'center', width: '100%', paddingVertical: 10 },
  trendsTitle: { fontSize: 15, fontWeight: '800', color: '#0F172A', marginBottom: 14 },
  trendRow: { marginBottom: 12 },
  trendRowHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  trendCatName: { fontSize: 12, color: '#334155', fontWeight: '700' },
  trendCatValue: { fontSize: 12, color: '#64748B', fontWeight: '600' },
  trendBarTrack: { height: 8, backgroundColor: '#F1F5F9', borderRadius: 4, overflow: 'hidden' },
  trendBarFill: { height: '100%', borderRadius: 4 },
  insightCard: { backgroundColor: '#ECFDF5', borderRadius: 18, padding: 16, marginHorizontal: 20, marginBottom: 20, borderWidth: 1, borderColor: '#A7F3D0' },
  insightHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 6 },
  insightSparkle: { fontSize: 16 },
  insightTitle: { fontSize: 14, fontWeight: '800', color: '#047857' },
  insightBody: { fontSize: 13, color: '#065F46', lineHeight: 19 },
  monthlyHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, marginBottom: 10 },
  monthlyHeaderTitle: { fontSize: 16, fontWeight: '800', color: '#0F172A' },
  monthlyCountBadge: { fontSize: 12, fontWeight: '800', color: green, backgroundColor: '#E6F9F2', paddingHorizontal: 9, paddingVertical: 2, borderRadius: 10 },
  advancedHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 44, paddingBottom: 16 },
  advancedTitleContainer: { flex: 1, marginLeft: 14 },
  advancedHeaderTitle: { fontSize: 20, fontWeight: '800', color: '#0F172A', lineHeight: 24 },
  advancedHeaderSubtitle: { fontSize: 20, fontWeight: '800', color: '#0F172A', lineHeight: 24 },
  advancedMonthPill: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F1F5F9', borderRadius: 14, paddingHorizontal: 12, paddingVertical: 7, gap: 6 },
  advancedMonthPillText: { fontSize: 13, fontWeight: '700', color: '#334155' },
  advancedMonthChevron: { fontSize: 11, color: '#64748B', fontWeight: '800' },
  advancedMonthDropdown: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#fff', borderRadius: 16, paddingHorizontal: 16, paddingVertical: 10, marginHorizontal: 20, marginBottom: 16, shadowColor: '#64748B', shadowOpacity: 0.1, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 3 },
  advCard: { backgroundColor: '#fff', borderRadius: 24, padding: 20, marginHorizontal: 20, marginBottom: 16, shadowColor: '#64748B', shadowOpacity: 0.08, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
  advCardTitle: { fontSize: 17, fontWeight: '800', color: '#0F172A', marginBottom: 16 },
  weeklyChartContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', height: 130, paddingTop: 6 },
  weeklyCol: { alignItems: 'center', flex: 1 },
  weeklyValText: { fontSize: 10, fontWeight: '700', color: '#64748B', marginBottom: 6, height: 14 },
  weeklyBarTrack: { width: 28, height: 85, justifyContent: 'flex-end', alignItems: 'center' },
  weeklyBarFill: { width: '100%', borderRadius: 8 },
  weeklyDayText: { fontSize: 12, fontWeight: '600', color: '#94A3B8', marginTop: 8 },
  weeklyDayTextActive: { color: green, fontWeight: '800' },
  compareLegendRow: { flexDirection: 'row', gap: 14, marginBottom: 16 },
  legendBadge: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendBox: { width: 12, height: 12, borderRadius: 3 },
  legendBadgeText: { fontSize: 12, fontWeight: '700', color: '#475569' },
  compareSection: { marginBottom: 16 },
  compareHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  compareLabel: { fontSize: 13, fontWeight: '800', color: '#1E293B' },
  compareValues: { fontSize: 11, fontWeight: '600', color: '#64748B' },
  compareBarStack: { gap: 5 },
  compareTrack: { height: 8, backgroundColor: '#F1F5F9', borderRadius: 4, overflow: 'hidden' },
  compareFill: { height: '100%', borderRadius: 4 },
  topCatRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 14 },
  topCatRank: { fontSize: 12, fontWeight: '700', color: '#94A3B8', width: 24 },
  topCatIconCircle: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  topCatInfo: { flex: 1 },
  topCatHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  topCatName: { fontSize: 14, fontWeight: '800', color: '#1E293B' },
  topCatValueRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  topCatAmount: { fontSize: 14, fontWeight: '800', color: '#0F172A' },
  topCatPercent: { fontSize: 11, fontWeight: '600', color: '#94A3B8' },
  topCatTrack: { height: 6, backgroundColor: '#F1F5F9', borderRadius: 3, overflow: 'hidden' },
  topCatFill: { height: '100%', borderRadius: 3 },
  advancedBannerCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#fff', borderRadius: 20, padding: 16, marginHorizontal: 20, marginBottom: 20, borderWidth: 1, borderColor: '#E2E8F0', shadowColor: '#64748B', shadowOpacity: 0.08, shadowRadius: 10, shadowOffset: { width: 0, height: 3 }, elevation: 3 },
  advancedBannerContent: { flexDirection: 'row', alignItems: 'center', flex: 1, marginRight: 10 },
  advancedBannerIconTile: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#E6F9F2', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  advancedBannerTextGroup: { flex: 1 },
  advancedBannerTitle: { fontSize: 15, fontWeight: '800', color: '#0F172A' },
  advancedBannerSubtitle: { fontSize: 11, fontWeight: '600', color: '#64748B', marginTop: 2 },
  advancedBannerArrow: { fontSize: 18, fontWeight: '800', color: green },
  budgetAlertCard: { backgroundColor: '#FEF2F2', borderRadius: 20, padding: 16, marginHorizontal: 20, marginBottom: 16, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#FCA5A5' },
  budgetAlertIconBox: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#FEE2E2', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  budgetAlertIcon: { fontSize: 20 },
  budgetAlertTextGroup: { flex: 1 },
  budgetAlertTitle: { fontSize: 15, fontWeight: '800', color: '#991B1B' },
  budgetAlertMessage: { fontSize: 12, color: '#B91C1C', marginTop: 3, lineHeight: 17 },
  budgetEmptyCard: { backgroundColor: '#fff', borderRadius: 24, padding: 24, marginHorizontal: 20, marginBottom: 16, alignItems: 'center', shadowColor: '#64748B', shadowOpacity: 0.08, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
  budgetEmptyIconCircle: { width: 60, height: 60, borderRadius: 20, backgroundColor: '#E6F9F2', alignItems: 'center', justifyContent: 'center', marginBottom: 14 },
  budgetEmptyTitle: { fontSize: 18, fontWeight: '800', color: '#0F172A' },
  budgetEmptyText: { fontSize: 13, color: '#64748B', textAlign: 'center', marginTop: 6, lineHeight: 20 },
  budgetCardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  budgetTotalSummaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  budgetTotalLabel: { fontSize: 12, color: '#64748B', fontWeight: '700' },
  budgetTotalValues: { fontSize: 12, color: '#0F172A', fontWeight: '800' },
  budgetTotalTrack: { height: 8, backgroundColor: '#F1F5F9', borderRadius: 4, overflow: 'hidden' },
  budgetTotalFill: { height: '100%', borderRadius: 4 },
  categoryBudgetRow: { marginTop: 14 },
  categoryBudgetTopLine: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  categoryBudgetLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  categoryBudgetName: { fontSize: 14, fontWeight: '800', color: '#1E293B' },
  categoryBudgetRight: { alignItems: 'flex-end' },
  categoryBudgetValue: { fontSize: 13, fontWeight: '700', color: '#475569' },
  categoryBudgetExceededValue: { fontSize: 13, fontWeight: '800', color: '#EF4444' },
  categoryBudgetExceededBadge: { fontSize: 11, fontWeight: '800', color: '#EF4444', marginTop: 1 },
  categoryBudgetTrack: { height: 8, backgroundColor: '#F1F5F9', borderRadius: 4, overflow: 'hidden' },
  categoryBudgetFill: { height: '100%', borderRadius: 4 },
  tipsCard: { backgroundColor: '#FFFBEB', borderRadius: 20, padding: 18, marginHorizontal: 20, marginBottom: 20, borderWidth: 1, borderColor: '#FDE68A' },
  tipsHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  tipsLightbulb: { fontSize: 18 },
  tipsTitle: { fontSize: 15, fontWeight: '800', color: '#92400E' },
  tipItemRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginTop: 8 },
  tipNumBadge: { width: 20, height: 20, borderRadius: 10, backgroundColor: '#FDE68A', alignItems: 'center', justifyContent: 'center' },
  tipNumText: { fontSize: 11, fontWeight: '800', color: '#92400E' },
  tipItemText: { fontSize: 12, color: '#78350F', flex: 1, lineHeight: 18 },
  editBudgetRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  editBudgetCatName: { fontSize: 14, fontWeight: '800', color: '#1E293B', flex: 1, marginLeft: 10 },
  editBudgetInputBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12, paddingHorizontal: 10, width: 120, height: 40 },
  editBudgetCurrency: { fontSize: 14, fontWeight: '800', color: '#64748B', marginRight: 4 },
  editBudgetInput: { fontSize: 14, fontWeight: '800', color: '#0F172A', flex: 1, paddingVertical: 0 },
  editBudgetSubtitle: { fontSize: 12, color: 'rgba(255,255,255,0.75)', textAlign: 'center', marginTop: 4 },
  profileHeaderSection: { alignItems: 'center', paddingTop: 44, paddingBottom: 20 },
  profileAvatarLarge: { width: 80, height: 80, borderRadius: 40, backgroundColor: '#0FBD89', alignItems: 'center', justifyContent: 'center', shadowColor: '#0BA576', shadowOpacity: 0.25, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 4, marginBottom: 12 },
  profileAvatarText: { color: '#fff', fontSize: 30, fontWeight: '800' },
  profileName: { fontSize: 22, fontWeight: '800', color: '#0F172A' },
  profileEmail: { fontSize: 13, color: '#64748B', marginTop: 3 },
  editProfileButton: { marginTop: 12, paddingHorizontal: 16, paddingVertical: 6, borderRadius: 16, borderWidth: 1, borderColor: '#CBD5E1', backgroundColor: '#fff' },
  editProfileButtonText: { fontSize: 13, fontWeight: '700', color: '#334155' },
  profileSectionGroup: { marginHorizontal: 20, marginBottom: 20 },
  profileSectionHeading: { fontSize: 12, fontWeight: '800', color: '#94A3B8', letterSpacing: 0.8, marginBottom: 8 },
  profileCard: { backgroundColor: '#fff', borderRadius: 20, paddingHorizontal: 16, paddingVertical: 4, shadowColor: '#64748B', shadowOpacity: 0.06, shadowRadius: 10, shadowOffset: { width: 0, height: 3 }, elevation: 2 },
  profileRowItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13 },
  profileRowIconTile: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  profileRowLabel: { flex: 1, fontSize: 14, fontWeight: '700', color: '#1E293B' },
  profileRowRight: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  profileRowValue: { fontSize: 13, fontWeight: '600', color: '#64748B' },
  profileRowChevron: { fontSize: 18, fontWeight: '700', color: '#CBD5E1' },
  profileDivider: { height: 1, backgroundColor: '#F1F5F9' },
  currencyModalCard: { backgroundColor: '#fff', borderRadius: 24, padding: 20, width: '85%', alignSelf: 'center', shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 16, elevation: 5 },
  currencyModalTitle: { fontSize: 16, fontWeight: '800', color: '#0F172A', marginBottom: 16, textAlign: 'center' },
  currencyOptionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 12, borderRadius: 12, marginBottom: 6 },
  currencyOptionSelected: { backgroundColor: '#E6F9F2' },
  currencyOptionText: { fontSize: 14, fontWeight: '700', color: '#1E293B' },
  importTextInput: { height: 120, borderRadius: 14, backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#E2E8F0', padding: 12, marginTop: 12, width: '100%', fontSize: 12, color: '#0F172A', textAlignVertical: 'top' },
  addCatTriggerButton: { height: 48, borderRadius: 16, backgroundColor: '#E6F9F2', borderStyle: 'dashed', borderWidth: 1.5, borderColor: green, alignItems: 'center', justifyContent: 'center', marginVertical: 14 },
  addCatTriggerText: { color: green, fontSize: 14, fontWeight: '800' },
  addCatFormBox: { backgroundColor: '#F8FAFC', borderRadius: 18, padding: 16, marginVertical: 14, borderWidth: 1, borderColor: '#E2E8F0' },
  addCatFormTitle: { fontSize: 15, fontWeight: '800', color: '#0F172A', marginBottom: 10 },
  addCatInput: { height: 44, borderRadius: 12, backgroundColor: '#fff', borderWidth: 1, borderColor: '#CBD5E1', paddingHorizontal: 12, fontSize: 14, color: '#0F172A', marginBottom: 12 },
  addCatPickerLabel: { fontSize: 12, fontWeight: '700', color: '#64748B', marginBottom: 6 },
  addCatIconPickerGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  addCatIconChoice: { width: 36, height: 36, borderRadius: 10, backgroundColor: '#fff', borderWidth: 1, borderColor: '#E2E8F0', alignItems: 'center', justifyContent: 'center' },
  addCatIconChoiceSelected: { borderColor: green, backgroundColor: '#E6F9F2' },
  addCatColorPickerGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  addCatColorChoice: { width: 26, height: 26, borderRadius: 13, borderWidth: 2, borderColor: 'transparent' },
  addCatColorChoiceSelected: { borderColor: '#0F172A' },
  addCatFormActions: { flexDirection: 'row', gap: 10 },
  addCatCancelBtn: { flex: 1, height: 42, borderRadius: 12, backgroundColor: '#E2E8F0', alignItems: 'center', justifyContent: 'center' },
  addCatCancelText: { color: '#475569', fontSize: 13, fontWeight: '800' },
  addCatSaveBtn: { flex: 1, height: 42, borderRadius: 12, backgroundColor: green, alignItems: 'center', justifyContent: 'center' },
  addCatSaveText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  removeCatButton: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10, backgroundColor: '#FEF2F2' },
  removeCatText: { color: '#EF4444', fontSize: 11, fontWeight: '800' },
  defaultCatTag: { color: '#94A3B8', fontSize: 11, fontWeight: '700' },
  darkAuthScreen: { flex: 1 },
  darkAuthScrollContent: { paddingHorizontal: 20, paddingTop: 52, paddingBottom: 40 },
  darkAuthHero: { alignItems: 'center', marginBottom: 24 },
  darkAuthLogoBadge: { width: 64, height: 64, borderRadius: 22, alignItems: 'center', justifyContent: 'center', shadowColor: '#10B981', shadowOpacity: 0.5, shadowRadius: 16, shadowOffset: { width: 0, height: 6 }, elevation: 6, marginBottom: 12 },
  darkAuthLogoSymbol: { fontSize: 32, fontWeight: '900', color: '#000000' },
  darkAuthBrandName: { fontSize: 26, fontWeight: '900', color: '#FFFFFF', letterSpacing: 0.5 },
  darkAuthTagline: { fontSize: 13, fontWeight: '600', color: '#10B981', marginTop: 4 },
  darkAuthCard: { backgroundColor: 'rgba(9, 21, 16, 0.92)', borderRadius: 28, padding: 22, borderWidth: 1.5, borderColor: 'rgba(16, 185, 129, 0.3)', shadowColor: '#10B981', shadowOpacity: 0.2, shadowRadius: 24, shadowOffset: { width: 0, height: 8 }, elevation: 4 },
  darkAuthToggleRow: { flexDirection: 'row', backgroundColor: '#040C08', borderRadius: 16, padding: 4, marginBottom: 20, borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.2)' },
  darkAuthToggleTab: { flex: 1, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  darkAuthToggleTabActiveGradient: { flex: 1, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  darkAuthToggleText: { fontSize: 14, fontWeight: '700', color: '#94A3B8' },
  darkAuthToggleTextActive: { color: '#000000', fontWeight: '800', fontSize: 14 },
  darkAuthHeadingTitle: { fontSize: 20, fontWeight: '800', color: '#FFFFFF', textAlign: 'center' },
  darkAuthHeadingSub: { fontSize: 12, color: '#94A3B8', textAlign: 'center', marginTop: 4, marginBottom: 20, lineHeight: 18 },
  darkAuthInputContainer: { marginBottom: 14 },
  darkAuthInputLabel: { fontSize: 12, fontWeight: '700', color: '#A7F3D0', marginBottom: 6 },
  darkAuthInputBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#040C08', borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.25)', borderRadius: 14, paddingHorizontal: 14, height: 48, gap: 10 },
  darkAuthTextInput: { flex: 1, fontSize: 14, color: '#FFFFFF', paddingVertical: 0 },
  darkAuthForgotRow: { alignItems: 'flex-end', marginBottom: 18 },
  darkAuthForgotText: { fontSize: 12, fontWeight: '700', color: '#10B981' },
  darkAuthSubmitBtnGradient: { height: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center', shadowColor: '#10B981', shadowOpacity: 0.4, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 4, marginTop: 6 },
  darkAuthSubmitText: { fontSize: 15, fontWeight: '800', color: '#000000' },
  darkAuthDividerRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 20 },
  darkAuthDividerLine: { flex: 1, height: 1, backgroundColor: 'rgba(255, 255, 255, 0.1)' },
  darkAuthDividerText: { fontSize: 11, fontWeight: '800', color: '#64748B', marginHorizontal: 10 },
  darkAuthSocialRow: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  darkAuthSocialTile: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, height: 46, borderRadius: 14, backgroundColor: '#040C08', borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.2)' },
  darkAuthSocialText: { fontSize: 13, fontWeight: '700', color: '#E2E8F0' },
  darkAuthGuestBtn: { alignItems: 'center', paddingVertical: 10 },
  darkAuthGuestText: { fontSize: 13, fontWeight: '700', color: '#94A3B8' },
  exactAuthContainer: { flex: 1 },
  exactAuthGlowTopRight: { position: 'absolute', top: -80, right: -80, width: 340, height: 340, borderRadius: 170, backgroundColor: 'rgba(16, 185, 129, 0.35)' },
  exactAuthScrollContent: { paddingHorizontal: 20, paddingTop: 48, paddingBottom: 36, alignItems: 'center' },
  exactAuthCard: { width: '100%', backgroundColor: 'rgba(15, 27, 21, 0.72)', borderRadius: 32, padding: 24, borderWidth: 1.5, borderColor: 'rgba(16, 185, 129, 0.35)', shadowColor: '#10B981', shadowOpacity: 0.25, shadowRadius: 24, shadowOffset: { width: 0, height: 10 }, elevation: 6 },
  exactAuthLogoHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, marginBottom: 20 },
  exactAuthLogoCircle: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#10B981', alignItems: 'center', justifyContent: 'center' },
  exactAuthLogoRupee: { fontSize: 19, fontWeight: '900', color: '#000000' },
  exactAuthLogoTextMain: { fontSize: 22, fontWeight: '900', color: '#FFFFFF' },
  exactAuthLogoTextGreen: { color: '#10B981' },
  exactAuthTitleLine1: { fontSize: 26, fontWeight: '900', color: '#FFFFFF', textAlign: 'center', lineHeight: 32 },
  exactAuthTitleLine2: { fontSize: 26, fontWeight: '900', color: '#10B981', textAlign: 'center', lineHeight: 32, marginBottom: 8 },
  exactAuthSubhead: { fontSize: 13, color: '#94A3B8', textAlign: 'center', marginBottom: 24, paddingHorizontal: 10, lineHeight: 19 },
  exactAuthInputGroup: { marginBottom: 16 },
  exactAuthFieldLabel: { fontSize: 14, fontWeight: '600', color: '#E2E8F0', marginBottom: 6 },
  exactAuthInputBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(4, 16, 11, 0.85)', borderWidth: 1.5, borderColor: '#10B981', borderRadius: 16, paddingHorizontal: 16, height: 50 },
  exactAuthTextInput: { flex: 1, fontSize: 14, color: '#FFFFFF', paddingVertical: 0 },
  exactAuthPasswordIconsRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  exactAuthSubmitTouchable: { marginTop: 10, marginBottom: 14 },
  exactAuthSubmitPill: { height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center', shadowColor: '#10B981', shadowOpacity: 0.6, shadowRadius: 18, shadowOffset: { width: 0, height: 6 }, elevation: 6 },
  exactAuthSubmitPillText: { fontSize: 16, fontWeight: '800', color: '#FFFFFF' },
  exactAuthForgotLinkBtn: { alignItems: 'center', marginVertical: 6 },
  exactAuthForgotLinkText: { fontSize: 14, fontWeight: '600', color: '#10B981' },
  exactAuthDividerRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 22 },
  exactAuthDividerLine: { flex: 1, height: 1, backgroundColor: 'rgba(255, 255, 255, 0.12)' },
  exactAuthDividerText: { fontSize: 13, color: '#94A3B8', marginHorizontal: 12 },
  exactAuthSocialRow: { flexDirection: 'row', justifyContent: 'center', gap: 18, marginBottom: 6 },
  exactAuthSocialTile: { width: 56, height: 56, borderRadius: 18, backgroundColor: 'rgba(255, 255, 255, 0.07)', borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.3)', alignItems: 'center', justifyContent: 'center', shadowColor: '#10B981', shadowOpacity: 0.3, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
  exactAuthBottomLinkRow: { flexDirection: 'row', alignItems: 'center', marginTop: 24 },
  exactAuthBottomLinkText: { fontSize: 14, color: '#94A3B8' },
  exactAuthBottomLinkAction: { fontSize: 14, fontWeight: '700', color: '#10B981' },
  darkHomeContainer: { flex: 1 },
  darkHomeScrollContent: { paddingBottom: 110 },
  darkHomeHero: { paddingHorizontal: 20, paddingTop: 44, paddingBottom: 20 },
  darkHomeAvatar: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', shadowColor: '#10B981', shadowOpacity: 0.4, shadowRadius: 10, elevation: 4 },
  darkHomeAvatarText: { color: '#000000', fontSize: 18, fontWeight: '900' },
  darkHomeGreetingSmall: { fontSize: 12, color: '#A7F3D0', fontWeight: '600' },
  darkHomeGreetingName: { fontSize: 18, color: '#FFFFFF', fontWeight: '800' },
  darkHomeHeaderButton: { width: 40, height: 40, borderRadius: 14, backgroundColor: 'rgba(15, 27, 21, 0.8)', borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.3)', alignItems: 'center', justifyContent: 'center' },
  darkHomeBalanceLabel: { fontSize: 13, color: '#94A3B8', fontWeight: '600', marginTop: 18 },
  darkHomeBalance: { fontSize: 34, fontWeight: '900', color: '#FFFFFF', marginTop: 2, marginBottom: 18 },
  darkHomeSummaryCard: { flex: 1, backgroundColor: 'rgba(15, 27, 21, 0.75)', borderRadius: 20, padding: 14, borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.25)' },
  darkHomeIncomeLabel: { fontSize: 12, fontWeight: '800', color: '#10B981' },
  darkHomeIncomeValue: { fontSize: 17, fontWeight: '800', color: '#FFFFFF', marginTop: 4 },
  darkHomeExpenseLabel: { fontSize: 12, fontWeight: '800', color: '#EF4444' },
  darkHomeExpenseValue: { fontSize: 17, fontWeight: '800', color: '#FFFFFF', marginTop: 4 },
  darkHomeBudgetCard: { backgroundColor: 'rgba(15, 27, 21, 0.85)', borderRadius: 22, padding: 18, marginHorizontal: 20, borderWidth: 1.5, borderColor: 'rgba(16, 185, 129, 0.35)', shadowColor: '#10B981', shadowOpacity: 0.2, shadowRadius: 16, elevation: 4 },
  darkHomeBudgetTitle: { fontSize: 15, fontWeight: '800', color: '#FFFFFF' },
  darkHomeBudgetAmount: { fontSize: 13, fontWeight: '800', color: '#10B981' },
  darkHomeProgressTrack: { height: 8, backgroundColor: '#040C08', borderRadius: 4, overflow: 'hidden', marginVertical: 10 },
  darkHomeProgressFill: { height: '100%', borderRadius: 4 },
  darkHomeBudgetHint: { fontSize: 12, color: '#94A3B8', fontWeight: '600' },
  darkHomeTransactionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, marginTop: 20, marginBottom: 12 },
  darkHomeTransactionTitle: { fontSize: 17, fontWeight: '800', color: '#FFFFFF' },
  darkHomeSeeAll: { fontSize: 13, fontWeight: '800', color: '#10B981' },
  darkHomeTransactionRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(15, 27, 21, 0.7)', borderRadius: 18, padding: 14, marginHorizontal: 20, marginBottom: 10, borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.2)' },
  darkHomeCatIconTile: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  darkHomeRowTitle: { fontSize: 15, fontWeight: '800', color: '#FFFFFF' },
  darkHomeRowSub: { fontSize: 11, color: '#94A3B8', marginTop: 2 },
  darkHomeRowNote: { fontSize: 11, color: '#A7F3D0', marginTop: 2 },
  darkHomeRowAmount: { fontSize: 15, fontWeight: '800', color: '#EF4444' },
  darkHomeIncomeAmountText: { color: '#10B981' },
  darkHomeEmptyCard: { backgroundColor: 'rgba(15, 27, 21, 0.7)', borderRadius: 20, padding: 24, marginHorizontal: 20, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.2)' },
  darkHomeEmptyIconTile: { width: 50, height: 50, borderRadius: 16, backgroundColor: 'rgba(16, 185, 129, 0.15)', alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  darkHomeEmptyTitle: { fontSize: 16, fontWeight: '800', color: '#FFFFFF' },
  darkHomeEmptyMessage: { fontSize: 12, color: '#94A3B8', textAlign: 'center', marginTop: 4 },
  darkHomeNavContainer: { flexDirection: 'row', height: 68, backgroundColor: 'rgba(3, 10, 6, 0.95)', borderTopWidth: 1, borderTopColor: 'rgba(16, 185, 129, 0.2)', alignItems: 'center', justifyContent: 'space-around', position: 'absolute', bottom: 0, left: 0, right: 0 },
  darkHomeFloatingTouchable: { position: 'absolute', bottom: 32, alignSelf: 'center', zIndex: 10 },
  darkHomeFloatingBtnPill: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', shadowColor: '#10B981', shadowOpacity: 0.6, shadowRadius: 16, shadowOffset: { width: 0, height: 6 }, elevation: 6 },
  lightAuthContainer: { flex: 1, backgroundColor: '#F8FAFC' },
  lightAuthCard: { width: '100%', backgroundColor: '#FFFFFF', borderRadius: 32, padding: 24, borderWidth: 1, borderColor: '#E2E8F0', shadowColor: '#64748B', shadowOpacity: 0.08, shadowRadius: 20, shadowOffset: { width: 0, height: 8 }, elevation: 4 },
  lightAuthInputBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F8FAFC', borderWidth: 1.5, borderColor: green, borderRadius: 16, paddingHorizontal: 16, height: 50 },
  lightAuthTextInput: { flex: 1, fontSize: 14, color: '#0F172A', paddingVertical: 0 },
  lightAuthSocialTile: { width: 56, height: 56, borderRadius: 18, backgroundColor: '#F1F5F9', borderWidth: 1, borderColor: '#E2E8F0', alignItems: 'center', justifyContent: 'center' },
  darkProfileCard: { backgroundColor: 'rgba(15, 27, 21, 0.85)', borderRadius: 20, borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.25)', overflow: 'hidden' },
  darkProfileRowLabel: { fontSize: 14, fontWeight: '700', color: '#FFFFFF', flex: 1 },
  darkProfileSectionHeading: { fontSize: 11, fontWeight: '800', color: '#10B981', letterSpacing: 0.8, marginBottom: 8, paddingLeft: 4 },
  darkEditProfileModalCard: { width: '88%', backgroundColor: '#091510', borderRadius: 24, padding: 22, borderWidth: 1.5, borderColor: 'rgba(16, 185, 129, 0.35)' },
  darkEditInput: { backgroundColor: '#040C08', borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.3)', borderRadius: 14, paddingHorizontal: 14, height: 46, fontSize: 14, color: '#FFFFFF', marginTop: 4, marginBottom: 12 },
  dateGroupHeaderRow: { paddingHorizontal: 20, paddingTop: 14, paddingBottom: 6 },
  dateGroupHeaderLabel: { fontSize: 13, fontWeight: '700', color: '#64748B' },
  darkDateGroupHeaderLabel: { fontSize: 13, fontWeight: '700', color: '#10B981' },
  seeMoreButton: { height: 48, borderRadius: 16, backgroundColor: '#E6F9F2', alignItems: 'center', justifyContent: 'center', marginHorizontal: 20, marginTop: 12, marginBottom: 20, borderWidth: 1, borderColor: green },
  darkSeeMoreButton: { backgroundColor: 'rgba(15, 27, 21, 0.85)', borderColor: 'rgba(16, 185, 129, 0.3)' },
  seeMoreText: { fontSize: 14, fontWeight: '800', color: green }
});
